name: com_russia_game_flutter_ui
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  chewie: ^1.11.3
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  flutter_colorpicker: ^1.1.0
  flutter_layout_grid: ^2.0.7
  flutter_svg: 2.1.0
  gradient_borders: ^1.0.1
  percent_indicator: ^4.2.3
  figma_squircle: ^0.6.3
  flutter_inner_shadow: ^0.0.1

  # State management / Injection
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  equatable: ^2.0.5

  # Routing
  go_router: ^14.1.0

  # Platform / device
  connectivity_plus: ^6.1.4
  device_preview: 1.2.0
  in_app_update: ^4.2.3
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

  # File system / data
  disk_space_plus: ^0.2.6
  es_compression: ^2.0.14
  open_filex: ^4.7.0
  path: ^1.9.1
  pool: ^1.5.1

  # Network
  dio: ^5.8.0+1
  http: ^1.4.0
  url_launcher: ^6.3.1

  # Utils
  convert: ^3.1.2
  dartz: ^0.10.1
  intl: ^0.20.2
  upgrader: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_utils: ^2.8.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/video/
    - assets/webp/
    - assets/webp/launcher/referral_program/

  fonts:
    - family: Halvar Engschrift
      fonts:
        - asset: assets/font/HalvarEng-X-Bd-Slanted.ttf
          weight: 800
        - asset: assets/font/HalvarEng-Bd.ttf
          weight: 700
        - asset: assets/font/HalvarEng-Bd-Slanted.ttf
          weight: 600
        - asset: assets/font/HalvarEng-Md.ttf
          weight: 500
        - asset: assets/font/HalvarEng-Rg.ttf
          weight: 400
    - family: St Nizhegorodsky
      fonts:
        - asset: assets/font/ST-Nizhegorodsky.ttf
          weight: 400
    - family: Akrobat
      fonts:
        - asset: assets/font/Akrobat-Regular.otf
          weight: 400
        - asset: assets/font/Akrobat-SemiBold.otf
          weight: 600
        - asset: assets/font/Akrobat-Bold.otf
          weight: 700
        - asset: assets/font/Akrobat-ExtraBold.otf
          weight: 800
        - asset: assets/font/Akrobat-Black.otf
          weight: 900
    - family: Dihjauti
      fonts:
        - asset: assets/font/Dihjauti-Bold.otf
          weight: 700
flutter_intl:
  enabled: true
